sistema/applications/proveedores/urls.py
# Fecha de Creación: 16/02/2024
# Autor: Vivian Carolina Hincapie Escobar
# Última modificación: 16/05/2024

from django.urls import path
from applications.users.decorators import admin_required
from . import views

app_name='proveedores_app'

urlpatterns = [
    path('list_proveedores/',admin_required(views.ProveedoresListView.as_view()),name='list_proveedores'),
    path('proveedores/export/xls',admin_required(views.export_proveedores_to_excel), name='export_proveedores_excel'),
    path('proveedores/export/csv',admin_required(views.export_proveedores_to_csv), name='export_proveedores_cvs'),
    path('add_proveedor/',admin_required(views.ProveedoresCreateView.as_view()),name='add_proveedores'),
    path('edit_proveedor/<pk>',admin_required(views.ProveedorUpdateView.as_view()),name='update_proveedores'),
    path('delete_proveedor/<pk>',admin_required(views.ProveedoresDeleteView.as_view()),name='delete_proveedores'),
    path('proveedor_audit/',admin_required(views.ProveedoresAuditListView.as_view()),name='proveedor_audit'),

]

sistema/sistema/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.materiaprima.urls')),
    path('', include('applications.users.urls')),
    path('', include('applications.home.urls')),
    path('', include('applications.insumos.urls')),
    path('', include('applications.proveedores.urls')),
    path('', include('applications.pedidos.urls')),
    path('', include('applications.facturas.urls')),
    path('', include('applications.procesamiento.urls')),
    path('', include('applications.productoterminado.urls')),
    path('', include('applications.existencias.urls')),


] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

sistema/applications/proveedores/models.py
# Fecha de Creación: 04/02/2024
# Autor: Vivian Carolina Hincapie Escobar
# Última modificación: 11/05/2024

from django.db import models
from django.utils import timezone
from applications.users.models import User

class Proveedores(models.Model):
    '''Clase para la creación de la tabla proveedores en la base de datos'''
    prov_id=models.AutoField('id',primary_key=True)
    nit = models.IntegerField('NIT',unique=True)
    prov_nombre=models.CharField('Nombre',max_length=40)
    prov_telefono=models.CharField('Telefono',max_length=10)
    deleted = models.BooleanField(default=False)  # Campo para el borrado lógico
    created=models.DateTimeField(default= timezone.now)

    def __str__(self):
        return f"{self.prov_nombre}"
    
    def delete(self, using=None, keep_parents=False):
        '''Función para realizar el borrado lógico del proveedor'''
        self.deleted = True  # Marca el proveedor como inactivo en lugar de eliminarlo
        self.save(using=using)

class ProveedoresAudit(models.Model):
    '''Modelo para auditar cambios en los proveedores'''

    ACTION_CHOICES = [
        ('C', 'Creado'),
        ('U', 'Actualizado'),
        ('D', 'Borrado')
    ]

    changed_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    proveedor = models.ForeignKey(Proveedores,on_delete=models.CASCADE, related_name='audit_logs')
    action = models.CharField(max_length=1, choices=ACTION_CHOICES)
    details = models.TextField(blank=True, null=True)
    changed_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.get_action_display()} - {self.changed_by} ({self.changed_at})'

sistema/applications/proveedores/forms.py
# Fecha de Creación: 16/02/2024
# Autor: Vivian Carolina Hincapie Escobar
# Última modificación: 08/05/2024

import re
from django import forms
from django.core.exceptions import ValidationError
# Importación de modelos
from .models import Proveedores, ProveedoresAudit
from applications.users.models import User

class ProveedorCreateForm(forms.ModelForm):
    """Formulario para la creación de proveedores."""

    class Meta:
        model = Proveedores
        fields = (
            'nit',
            'prov_nombre',
            'prov_telefono',
        )

        widgets = {
            'nit': forms.NumberInput(attrs={'class': 'form-control'}),
            'prov_nombre': forms.TextInput(attrs={'placeholder': 'Nombre del Proveedor', 'class': 'form-control'}),
            'prov_telefono': forms.TextInput(attrs={'placeholder': 'Teléfono', 'type': 'number', 'class': 'form-control'}),
        }

    def clean_prov_telefono(self):
        '''Función que valida que el teléfono del proveedor tenga exactamente 10 dígitos.'''
        cantidad = self.cleaned_data['prov_telefono']
        if len(cantidad) < 10:
            raise forms.ValidationError("El teléfono debe tener al menos 10 dígitos.")
        elif len(cantidad) > 10:
            raise forms.ValidationError("El teléfono no debe tener más de 10 dígitos.")
        return cantidad
    
    def clean_prov_nombre(self):
        '''Función que valida que el nombre del proveedor no contenga caracteres especiales.'''
        nombre = self.cleaned_data['prov_nombre']
        if not re.match("^[a-zA-Z ]+$", nombre):
            raise forms.ValidationError("El nombre no debe contener números o caracteres especiales.")
        return nombre

class ProveedoresUpdateForm(forms.ModelForm):
    """Formulario para la actualización de proveedores."""

    class Meta:
        model = Proveedores
        fields = ['nit', 'prov_nombre', 'prov_telefono']

        widgets = {
            'nit': forms.NumberInput(attrs={'class': 'form-control'}),
            'prov_nombre': forms.TextInput(attrs={'placeholder': 'Nombre del Proveedor', 'class': 'form-control'}),
            'prov_telefono': forms.TextInput(attrs={'placeholder': 'Teléfono', 'type': 'number', 'class': 'form-control'}),
        }

    def clean_prov_telefono(self):
        '''Función que valida que el teléfono del proveedor tenga exactamente 10 dígitos.'''
        cantidad = self.cleaned_data['prov_telefono']
        if len(cantidad) < 10:
            raise forms.ValidationError("El teléfono debe tener al menos 10 dígitos.")
        elif len(cantidad) > 10:
            raise forms.ValidationError("El teléfono no debe tener más de 10 dígitos.")
        return cantidad
    
    def clean_prov_nombre(self):
        '''Función que valida que el nombre del proveedor no contenga caracteres especiales.'''
        nombre = self.cleaned_data['prov_nombre']
        if not re.match("^[a-zA-Z ]+$", nombre):
            raise forms.ValidationError("El nombre no debe contener números o caracteres especiales.")
        return nombre

class ProveedorAuditFilterForm(forms.Form):
    '''Formulario para filtrar en la vista de auditoría de proveedores.'''
    
    proveedor = forms.ModelChoiceField(
        queryset=Proveedores.objects.all(), 
        required=False, 
        label='Proveedor',
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    action = forms.ChoiceField(
        choices=ProveedoresAudit.ACTION_CHOICES, 
        required=False, 
        label='Acción',
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    changed_by = forms.ModelChoiceField(
        queryset=User.objects.all(), 
        required=False, 
        label='Cambios realizados por',
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    start_date = forms.DateField(
        label='Fecha inicial', 
        required=False, 
        widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'})
    )
    end_date = forms.DateField(
        label='Fecha final', 
        required=False, 
        widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'})
    )

sistema/applications/proveedores/views.py
# Fecha de Creación: 04/02/2024
# Autor: Vivian Carolina Hincapie Escobar
# Última modificación: 15/05/2024

from django.http import HttpResponse
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment
import csv
from django.contrib import messages
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
# Importación de modelos y formularios
from .models import Proveedores, ProveedoresAudit
from .forms import ProveedorCreateForm, ProveedoresUpdateForm, ProveedorAuditFilterForm

class ProveedoresListView(LoginRequiredMixin, ListView):
    '''Clase para mostrar los datos de los proveedores'''
    model = Proveedores
    template_name = "proveedores/list_proveedor.html"
    login_url = reverse_lazy('users_app:login')
    paginate_by = 10
    context_object_name = 'proveedor'

    def get_queryset(self):
        '''Función que toma de la barra de búsqueda la palabra clave para filtrar'''
        palabra_clave = self.request.GET.get("kword", '')
        lista = Proveedores.objects.filter(
            prov_nombre__icontains=palabra_clave,
            deleted=False  # Solo proveedores activos
        ).order_by('prov_nombre')  # Ordenar por 'prov_nombre'
        return lista
    
class ProveedoresCreateView(LoginRequiredMixin, CreateView):
    '''Clase para crear nuevos proveedores'''
    model = Proveedores
    template_name = "proveedores/add_proveedor.html"
    login_url = reverse_lazy('home_app:home')
    form_class = ProveedorCreateForm
    success_url = reverse_lazy('proveedores_app:list_proveedores')

    def form_valid(self, form):
        '''Validación del formulario para crear un nuevo proveedor'''
        nombre = form.cleaned_data['prov_nombre']
        messages.success(self.request, f'¡El proveedor {nombre} se ha agregado correctamente!')
        return super(ProveedoresCreateView, self).form_valid(form)

class ProveedorUpdateView(LoginRequiredMixin, UpdateView):
    '''Vista para actualizar los datos de proveedores'''
    model = Proveedores
    template_name = "proveedores/edit_proveedor.html"
    login_url = reverse_lazy('users_app:login')
    form_class = ProveedoresUpdateForm
    success_url = reverse_lazy('proveedores_app:list_proveedores')

    def form_valid(self, form):
        '''Validación del formulario para actualizar un proveedor'''
        nombre = form.cleaned_data['prov_nombre']
        messages.success(self.request, f'¡El proveedor {nombre} se ha actualizado correctamente!')
        return super(ProveedorUpdateView, self).form_valid(form)

class ProveedoresDeleteView(LoginRequiredMixin, DeleteView):
    '''Vista para borrar proveedores'''
    model = Proveedores
    template_name = "proveedores/delete_proveedor.html"
    login_url = reverse_lazy('users_app:login')
    success_url = reverse_lazy('proveedores_app:list_proveedores')

class ProveedoresAuditListView(LoginRequiredMixin, ListView):
    '''Clase para mostrar los datos de logs de proveedores'''
    model = ProveedoresAudit
    template_name = "administrador/auditorias/proveedoraudit.html"
    login_url = reverse_lazy('users_app:login')
    paginate_by = 10
    context_object_name = 'proveedor'

    def get_queryset(self):
        '''Obtiene y filtra el conjunto de registros de auditoría'''
        queryset = super().get_queryset()
        form = ProveedorAuditFilterForm(self.request.GET)

        if form.is_valid():
            proveedor = form.cleaned_data.get('proveedor')
            action = form.cleaned_data.get('action')
            changed_by = form.cleaned_data.get('changed_by')
            start_date = form.cleaned_data.get('start_date')
            end_date = form.cleaned_data.get('end_date')

            if proveedor:
                queryset = queryset.filter(proveedor=proveedor)
            if action:
                queryset = queryset.filter(action=action)
            if changed_by:
                queryset = queryset.filter(changed_by=changed_by)
            if start_date:
                queryset = queryset.filter(changed_at__gte=start_date)
            if end_date:
                end_date += timezone.timedelta(days=1)
                queryset = queryset.filter(changed_at__lt=end_date)

        return queryset

    def get_context_data(self, **kwargs):
        '''Agrega el formulario de filtro al contexto'''
        context = super().get_context_data(**kwargs)
        context['filter_form'] = ProveedorAuditFilterForm(self.request.GET)
        return context
    
def export_proveedores_to_excel(request):
    '''Vista para exportar datos de la tabla proveedores en formato Excel'''
    fecha_descarga = timezone.now().strftime("%Y-%m-%d %H:%M:%S")
    proveedores = Proveedores.objects.filter(deleted=False)  # Filtrar proveedores activos

    workbook = Workbook()
    worksheet = workbook.active
    worksheet.title = 'Proveedores'

    title_font = Font(bold=True)
    title_fill = PatternFill(start_color="FFFFFF00", end_color="FFFFFF00", fill_type="solid")  # Transparente
    title_alignment = Alignment(horizontal='center')
    
    worksheet.append(['TACO MAS'])
    worksheet.merge_cells('A1:C1')
    title_cell = worksheet['A1']
    title_cell.font = title_font
    title_cell.fill = title_fill
    title_cell.alignment = title_alignment

    worksheet.append(['Fecha de descarga:', fecha_descarga])
    worksheet.append(['Software:', 'Tacosoft'])
    worksheet.append([])  # Agregar una fila vacía

    headers = ['NIT', 'Razón Social', 'Teléfono']
    worksheet.append(headers)

    header_font = Font(bold=True)
    header_fill = PatternFill(start_color="CCCCCC", end_color="CCCCCC", fill_type="solid")  # Gris claro
    header_alignment = Alignment(horizontal='center')

    for col in range(1, len(headers) + 1):
        header_cell = worksheet.cell(row=worksheet.max_row, column=col)
        header_cell.font = header_font
        header_cell.fill = header_fill
        header_cell.alignment = header_alignment

    for proveedor in proveedores:
        data_row = [proveedor.nit, proveedor.prov_nombre, proveedor.prov_telefono]
        worksheet.append(data_row)

    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename=proveedores.xlsx'
    workbook.save(response)

    return response

def export_proveedores_to_csv(request):
    '''Vista para exportar datos de la tabla proveedores en formato CSV'''
    proveedores = Proveedores.objects.filter(deleted=False)  # Obtener datos de proveedores
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=proveedores.csv'

    writer = csv.writer(response)
    writer.writerow(['NIT', 'Razón Social', 'Teléfono'])  # Encabezados de columnas

    for proveedor in proveedores:
        writer.writerow([proveedor.nit, proveedor.prov_nombre, proveedor.prov_telefono])

    return response

sistema/templates/proveedores/add_proveedor.html
<!-- 
Titulo: Modal que muestra formulario para actualización
de datos de proveedores registrados en el sistema
Fecha Elaboración: 16/02/2024   
Última actualización: 06/05/2024
-->

<!-- Estructura del modal para añadir un proveedor -->
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content bg-dark text-white">
        <!-- Encabezado del modal -->
        <div class="modal-header">
            <h5 class="modal-title">Añadir Proveedor</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        
        <!-- Cuerpo del modal -->
        <div class="modal-body">
            <!-- Formulario para añadir un proveedor -->
            <form id="provAddForm" action="{% url 'proveedores_app:add_proveedores' %}" method="POST" class="form-control bg-dark text-white" style="--bs-bg-opacity: .5;">
                {% csrf_token %}
                
                <!-- Mostrar mensajes de error si existen -->
                {% if form.errors %}
                    <div class="alert alert-info">    
                        {{ form.errors.prov_nombre.0 }}
                        {{ form.errors.prov_telefono.0 }}
                    </div>
                {% endif %}

                <div class="mx-4 my-2 row">
                    <!-- Campo para el NIT del proveedor -->
                    <div class="mb-3 col-12">
                        <label for="id_nit" class="form-label">NIT:</label>
                        {{ form.nit }}
                    </div>
                    
                    <!-- Campo para la razón social del proveedor -->
                    <div class="mb-3 col-12">
                        <label for="id_prov_nombre" class="form-label">Razón Social:</label>
                        {{ form.prov_nombre }}
                    </div>

                    <!-- Campo para el teléfono del proveedor -->
                    <div class="mb-3 col-12">
                        <label for="id_prov_telefono" class="form-label">Teléfono:</label>
                        <br>
                        {{ form.prov_telefono }}
                    </div>

                    <!-- Botones para guardar o cancelar la acción -->
                    <div class="d-flex justify-content-center">
                        <div class="row">
                            <div class="col">
                                <button class="btn btn-success" type="submit">Guardar</button>
                                &nbsp;
                                <a href="{% url 'proveedores_app:list_proveedores' %}" type="button" class="btn btn-secondary">Cancelar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>    
    </div>
</div>

<!-- Script para manejar el envío del formulario mediante AJAX -->
<script>
    $(document).ready(function () {
        // Cuando el formulario se envíe
        $('#provAddForm').submit(function (event) {
            event.preventDefault(); // Evita la redirección predeterminada

            // Realiza la solicitud AJAX
            $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                data: $(this).serialize(),
                success: function (data) {
                    // Verifica la respuesta y actualiza el contenido del modal
                    $('#add_proveedor').html(data);
                },
                error: function (xhr, status, error) {
                    // Maneja errores de Ajax, si es necesario
                }
            });
        });
    });
</script>

sistema/templates/proveedores/edit_proveedor.html
<!-- 
Titulo: Modal que muestra formulario para editar datos de proveedores registrados en el sistema
Fecha Elaboración: 16/02/2024   
Última actualización: 06/05/2024
-->

<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content bg-dark text-white">
        <div class="modal-header">
            <h5 class="modal-title">Editar Proveedor</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form id="provEditForm" action="{% url 'proveedores_app:update_proveedores' object.prov_id %}" method="POST" class="form-control bg-dark text-white" style="--bs-bg-opacity: .5;">
                {% csrf_token %}
                {% if form.errors %}
                    <div class="alert alert-info">
                        {{form.errors.prov_nombre.0}}
                        {{form.errors.prov_telefono.0}}
                    </div>
                {% endif %}

                <div class="mx-4 my-2 row">
                    <div class="mb-3 col-12">
                        <label for="id_nit" class="form-label">NIT: </label>
                        {{form.nit}}
                    </div>

                    <div class="mb-3 col-12">
                        <label for="id_prov_nombre" class="form-label">Razón Social:</label>
                        {{form.prov_nombre}}
                    </div>

                    <div class="mb-3 col-12">
                        <label for="id_prov_telefono" class="form-label">Teléfono:</label>
                        <br>
                        {{form.prov_telefono}}
                    </div>

                    <div class="d-flex justify-content-center">
                        <div class="row">
                            <div class="col">
                                <button class="btn btn-success" type="submit">Guardar</button>
                                &nbsp;
                                <a href="{% url 'proveedores_app:list_proveedores' %}" type="button" class="btn btn-secondary">Cancelar</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        // Escucha el evento submit del formulario con id 'provEditForm'
        $('#provEditForm').submit(function (event) {
            event.preventDefault(); // Evita la redirección predeterminada del formulario

            // Realiza una solicitud Ajax
            $.ajax({
                type: 'POST', // Método de la solicitud
                url: $(this).attr('action'), // URL a la que se envía el formulario
                data: $(this).serialize(), // Datos serializados del formulario
                success: function (data) {
                    // Si la solicitud es exitosa, actualiza el contenido del modal
                    $('#update_proveedor').html(data);
                },
                error: function (xhr, status, error) {
                    // Maneja errores de la solicitud Ajax, si es necesario
                    console.error('Error en la solicitud:', error);
                }
            });
        });
    });
</script>

sistema/templates/proveedores/list_proveedor.html
<!-- 
Titulo: Template para mostrar proveedores registrados en el sistema
Fecha Elaboración: 16/02/2024   
Última actualización: 17/05/2024
-->

{% extends 'base.html' %}

{% block title %}
    Proveedores
{% endblock title %}

{% block content %}
<div class="mt-3 container">
    <!-- Mostrar mensajes de éxito -->
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ message|safe }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>                      
        {% endfor %}
    {% endif %}

    <!-- Tarjeta para acciones de proveedores -->
    <div class="card text-bg-dark mb-3">
        <div class="card-header">
            <div class="row">
                <div class="col-6">
                    <!-- Botón para agregar nuevo proveedor -->
                    <a name="" id="" class="btn btn-success" onclick="add_proveedor('{% url 'proveedores_app:add_proveedores' %}')" role="button">Agregar Proveedor</a>
                </div>
                <div class="col-6">
                    <!-- Formulario de búsqueda -->
                    <form class="d-flex" role="search">
                        {% csrf_token %}
                        <input class="form-control me-2" type="search" placeholder="Buscar Proveedor" aria-label="Search" name="kword" id="kword">
                        <button class="btn btn-outline-success" type="submit">Buscar</button>
                    </form>
                </div>
            </div>
        </div>

        <!-- Contenido de la tarjeta -->
        <div class="card-body">
            <div class="cart-title">
                <div class="mb-2 row">
                    <div class="col-4">
                        <h4>Proveedor</h4>
                    </div>
                    <div class="col-8 d-flex justify-content-end gap-2">
                        <!-- Dropdown para exportar datos -->
                        <div class="dropdown">
                            <a href="#" class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Descargar</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'proveedores_app:export_proveedores_excel' %}">Excel</a></li>
                                <li><a class="dropdown-item" href="{% url 'proveedores_app:export_proveedores_cvs' %}">CVS</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Tabla de proveedores -->
            <div class="table-responsive">
                <table class="table table-secondary">
                    <thead>
                        <tr>
                            <th scope="col">NIT</th>
                            <th scope="col">Razón Social</th>
                            <th scope="col">Teléfono</th>
                            <th scope="col" class="text-center">Detalles</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for p in proveedor %}
                        <tr>
                            <td>
                                <a onclick="update_proveedor('{% url 'proveedores_app:update_proveedores' p.prov_id %}')" type="button" style="color: blue; text-decoration-line: underline;" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-title="Editar">{{ p.nit }}</a>
                            </td>
                            <td>{{ p.prov_nombre }}</td>
                            <td>{{ p.prov_telefono }}</td>
                            <td>
                                <div class="d-flex justify-content-center">
                                    <a class="m-auto btn btn-danger" onclick="delete_proveedor('{% url 'proveedores_app:delete_proveedores' p.prov_id %}')" type="button"><i class="fa-solid fa-trash-can"></i></a>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- Paginación -->
    <div class="d-flex justify-content-center">
        <div class="row">
            <div class="col">
                {% if is_paginated %}
                    <nav aria-label="Page navigation example">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                            {% endif %}
                            {% for pagina in paginator.page_range %}
                                {% if pagina == page_obj.number %}
                                    <li class="page-item active" aria-current="page"><a class="page-link" href="?page={{ pagina }}">{{ pagina }}</a></li>
                                {% else %}
                                    <li class="page-item"><a class="page-link" href="?page={{ pagina }}">{{ pagina }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- Modales para agregar, eliminar y actualizar proveedores -->
<div class="modal fade" id="add_proveedor" role="dialog"></div>
<div class="modal fade" id="delete_proveedor" role="dialog"></div>
<div class="modal fade" id="update_proveedor" role="dialog"></div>

{% endblock content %}

{% block extrajs %}
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>

    <script>
        /**
         * Función para cargar el formulario de agregar proveedor en un modal.
         * @param {string} url - La URL de la vista que retorna el formulario.
         */

         async function add_proveedor(url) {
            // Realiza una solicitud fetch a la URL proporcionada.
            const response = await fetch(url);
            // Convierte la respuesta en texto HTML.
            const html = await response.text();
            // Inserta el HTML recibido en el elemento con id 'add_proveedor'.
            document.getElementById('add_proveedor').innerHTML = html;
            // Muestra el modal con el formulario cargado.
            $('#add_proveedor').modal('show');
        }

        async function delete_proveedor(url) {
            // Realiza una solicitud fetch a la URL proporcionada.
            const response = await fetch(url);
            // Convierte la respuesta en texto HTML.
            const html = await response.text();
            // Inserta el HTML recibido en el elemento con id 'delete_proveedor'.
            document.getElementById('delete_proveedor').innerHTML = html;
            // Muestra el modal con el formulario de eliminación cargado.
            $('#delete_proveedor').modal('show');
        }

        async function update_proveedor(url) {
            // Realiza una solicitud fetch a la URL proporcionada.
            const response = await fetch(url);
            // Convierte la respuesta en texto HTML.
            const html = await response.text();
            // Inserta el HTML recibido en el elemento con id 'update_proveedor'.
            document.getElementById('update_proveedor').innerHTML = html;
            // Muestra el modal con el formulario de actualización cargado.
            $('#update_proveedor').modal('show');
        }

        // Inicializa los tooltips de Bootstrap en los elementos que los requieren.
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
    </script>
{% endblock %}