sistema/applications/procesamiento/urls.py
from django.urls import path
from . import views

app_name='procesamientos_app'

urlpatterns = [
    path('procesamientos/',views.ProcesamientosView.as_view(),name='procesamientos'),
    path('select_coccion/',views.select_coccion_view,name='select_coccion'),
    path('select_picado/',views.select_picado_view, name='select_picado'),
    path('procesamiento_coccion/<int:producto_id>/',views.ingresar_peso_materias_primas_coccion,name='procesamiento_coccion'),
    path('procesamiento_picado/<int:producto_id>/',views.ingresar_peso_materias_primas_picado,name='procesamiento_picado'),
    path('caracteristicas_organolepticas/<str:lote>',views.caracteristicas_organolepticas_pt, name='caracteristicas_organolepticas'),
    path('ingresar_empaques/<str:lote>',views.empaque_vacio, name='empaques'),
    path('equipos/',views.EquiposListView.as_view(),name='equipos'),
    path('add_equipos/',views.EquiposcreateView.as_view(),name='add_equipos'),
    path('delete_equipo/<pk>',views.EquiposDeleteView.as_view(),name='delete_equipo'),
    path('edit_equipo/<pk>',views.EquiposUpdateView.as_view(),name='edit_equipo'),
    
]

sistema/sistema/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.materiaprima.urls')),
    path('', include('applications.users.urls')),
    path('', include('applications.home.urls')),
    path('', include('applications.insumos.urls')),
    path('', include('applications.proveedores.urls')),
    path('', include('applications.pedidos.urls')),
    path('', include('applications.facturas.urls')),
    path('', include('applications.procesamiento.urls')),
    path('', include('applications.productoterminado.urls')),
    path('', include('applications.existencias.urls')),


] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

sistema/applications/procesamiento/models.py
from django.db import models
from applications.productoterminado.models import ProductoTerminado
from applications.materiaprima.models import MateriaPrimaGenerica
from applications.users.models import User

class Picado(models.Model):

    ESTADO_CHOICES=(
        ('0','Aprobado'),
        ('1','No Aprobado'),

    )

    pica_id=models.AutoField(primary_key=True)
    pica_producto=models.ForeignKey(ProductoTerminado, on_delete=models.CASCADE)
    pica_cantidad_total = models.IntegerField('Cantidad',default=0)
    pica_pesoPostProcesamiento=models.FloatField('Peso',default=0)
    pica_merma=models.FloatField('Peso Merma',default=0)
    pica_check=models.CharField('estado',max_length=1, choices=ESTADO_CHOICES)
    
    def __str__(self):
        return f"{self.pica_producto}-{self.pica_cantidad_total}{self.pica_pesoPostProcesamiento}-{self.pica_merma}-{self.pica_check}"

class PicadoMateriaPrima(models.Model):
    picado = models.ForeignKey(Picado, on_delete=models.CASCADE)
    materia_prima = models.ForeignKey(MateriaPrimaGenerica, on_delete=models.CASCADE)
    cantidad = models.IntegerField()

    def __str__(self):
        return f"{self.picado} - {self.materia_prima} ({self.cantidad}g)"

class Coccion(models.Model):

    CHECK_CHOICES=(
        ('0','Aceptado'),
        ('1','Rechazado'),

    )

    cocc_id=models.AutoField(primary_key=True)
    cocc_producto=models.ForeignKey(ProductoTerminado, on_delete=models.CASCADE)
    cocc_cantidad_total = models.IntegerField('Cantidad',default=0)
    cocc_pesoPostProcesamiento=models.FloatField('Peso',default=0)
    cocc_merma=models.FloatField('Merma',default=0)
    cocc_tiempoCoccion=models.IntegerField('Tiempo de Coccion')
    cocc_temperaturafinal=models.FloatField('Temperatura final')
    cocc_check=models.CharField('estado',max_length=1, choices=CHECK_CHOICES,default="0")

    
    def __str__(self):
        return f"{self.cocc_producto}-{self.cocc_cantidad_total}-{self.cocc_pesoPostProcesamiento}-{self.cocc_merma}-{self.cocc_tiempoCoccion}-{self.cocc_temperaturafinal}-{self.cocc_check}"

class CoccionMateriaPrima(models.Model):
    coccion = models.ForeignKey(Coccion, on_delete=models.CASCADE)
    materia_prima = models.ForeignKey(MateriaPrimaGenerica, on_delete=models.CASCADE)
    cantidad = models.IntegerField()

    def __str__(self):
        return f"{self.coccion} - {self.materia_prima} ({self.cantidad}g)"
    
class Equipos(models.Model):

    CHECK_CHOICES=(
        ('0','Aprobado'),
        ('1','No Aprobado'),

    )

    id_equipo=models.AutoField(primary_key=True)
    equi_encargadoCocina=models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank= True, related_name='equipos_cocina')
    equi_encargadoEntrega=models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank= True, related_name='equipos_entrega')
    equi_nombre=models.CharField('Nombre', max_length=50, default="NULL")
    equi_check=models.CharField('estado',max_length=1, choices=CHECK_CHOICES, default="0")
    deleted = models.BooleanField(default=False) #Campo que corresponde al borrado logico

    def __str__(self):
        return f"{self.id_equipo}-{self.equi_encargadoCocina}-{self.equi_encargadoEntrega}-{self.equi_nombre}"
    
    def delete(self, using=None, keep_parents=False):
        '''Funcion para borrado lógico'''
        self.deleted = True  # Marcar como inactivo en lugar de eliminar
        self.save(using=using)

sistema/applications/procesamiento/views.py
#Importación de bibliotecas necesarias
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, ListView,CreateView,DeleteView,UpdateView
from django.urls import reverse_lazy
from applications.users.decorators import login_required
#Importación de modelos y formularios
from applications.productoterminado.models import (
    ProductoTerminadoGenerico, 
    ProductoTerminado,
    EmpaqueProductoTerminado,
    Vacio,
)
from .models import (
    Picado,
    PicadoMateriaPrima,
    Coccion,
    CoccionMateriaPrima,
    Equipos)
from .forms import addEquipos,EquiposUpdateForm
from applications.productoterminado.forms import (CaracteristicasOrganolepticasPTForm)

#Autor: Daniel Castro Mercado
class ProcesamientosView(LoginRequiredMixin, TemplateView):
    '''Clase para mostrar los datos de Procesamiento'''
    template_name = "Procesamientos/procesamiento_view.html"
    login_url=reverse_lazy('users_app:login')

#Autor: Daniel Castro Mercado
def select_coccion_view(request):
    '''Vista para seleccionar que producto de coccion se va a realizar'''
    productos = ProductoTerminadoGenerico.objects.filter(pt_tipo='0')
    if request.method == 'POST':
        # Procesar los datos del formulario aquí
        # Redirigir a la página de éxito o a donde sea necesario
        return redirect(reverse_lazy('procesamientos_app:procesamiento_coccion', kwargs={'producto_id': request.POST.get('producto_terminado')}))
    else:
        return render(request, 'procesamientos/coccion/select_coccion.html', {'productos': productos})

#Autor: Daniel Castro Mercado
def select_picado_view(request):
    '''Vista para seleccionar que producto de picado se va a realizar'''
    productos = ProductoTerminadoGenerico.objects.filter(pt_tipo='1')
    if request.method == 'POST':
        # Procesar los datos del formulario aquí
        # Redirigir a la página de éxito o a donde sea necesario
        return redirect(reverse_lazy('procesamientos_app:procesamiento_picado', kwargs={'producto_id': request.POST.get('producto_terminado')}))
    return render(request, 'procesamientos/picado/select_picado.html', {'productos': productos})

#Autor: Vivian carolina Hincapie Escobar
@login_required
def ingresar_peso_materias_primas_coccion(request, producto_id):
    '''
    Vista para ingresar el peso de las materias primas para el proceso de cocción.
    Crea instancias de ProductoTerminado, Coccion, y CoccionMateriaPrima.
    Deduce la cantidad del inventario de materias primas.
    '''  
    producto = get_object_or_404(ProductoTerminadoGenerico, id=producto_id)
    materias_primas = producto.materiaPrimaUsada.all()
    
    if request.method == 'POST':
         # Crear la instancia de ProductoTerminado
        producto_terminado = ProductoTerminado(
            pt_cantidad=0,  # Cantidad inicial es 0
            pt_nombre=producto,
            pt_fechapreparacion=timezone.now(),
            pt_fechavencimiento=timezone.now() + timezone.timedelta(days=20)  # Ajusta esto según tus necesidades
        )
        producto_terminado.save()
        
        # Después de guardar la instancia de ProductoTerminado, obtén el número de lote
        lote = producto_terminado.pt_lote

        # Crear la instancia de Picado
        coccion = Coccion(
            cocc_producto=producto_terminado,
            cocc_cantidad_total=request.POST['cocc_cantidad_total'],
            cocc_pesoPostProcesamiento=request.POST['cocc_pesoPostProcesamiento'],
            cocc_merma=request.POST['cocc_merma'],
            cocc_tiempoCoccion=request.POST['cocc_tiempoCoccion'],
            cocc_temperaturafinal=request.POST['cocc_temperaturafinal'],
            cocc_check=request.POST['cocc_check']
        )
        coccion.save()
        
         # Guardar los pesos de materias primas
        for materia_prima in materias_primas:
            peso = request.POST.get(f'peso_{materia_prima.id}')
            if peso:
                peso = int(peso)  # Convertir el peso a entero
                print(f'Guardando {peso}g de {materia_prima.mp_nombre}')
                coccion_materia_prima = CoccionMateriaPrima(
                    coccion=coccion,
                    materia_prima=materia_prima,
                    cantidad=peso
                )
                coccion_materia_prima.save()

                # Deducir la cantidad del inventario
                materia_prima.cantidad_total -= peso
                materia_prima.save()
        return redirect(reverse_lazy('procesamientos_app:caracteristicas_organolepticas', kwargs={'lote': lote}))
    return render(request, 'procesamientos/coccion/ingreso_peso_mp.html', {'producto': producto, 'materias_primas': materias_primas})
 
#Autor: Vivian carolina Hincapie Escobar
@login_required       
def ingresar_peso_materias_primas_picado(request, producto_id):
    '''
    Vista para ingresar el peso de las materias primas para el proceso de picado.
    Crea instancias de ProductoTerminado, Picado, y PicadoMateriaPrima.
    Deduce la cantidad del inventario de materias primas.
    '''
    producto = get_object_or_404(ProductoTerminadoGenerico, id=producto_id)
    materias_primas = producto.materiaPrimaUsada.all()
    
    if request.method == 'POST':
         # Crear la instancia de ProductoTerminado
        producto_terminado = ProductoTerminado(
            pt_cantidad=0,  # Cantidad inicial es 0
            pt_nombre=producto,
            pt_fechapreparacion=timezone.now(),
            pt_fechavencimiento=timezone.now() + timezone.timedelta(days=20)  # Ajusta esto según tus necesidades
        )
        producto_terminado.save()
        
        # Después de guardar la instancia de ProductoTerminado, obtén el número de lote
        lote = producto_terminado.pt_lote

        # Crear la instancia de Picado
        picado = Picado(
            pica_producto=producto_terminado,
            pica_cantidad_total=request.POST['pica_cantidad_total'],
            pica_pesoPostProcesamiento=request.POST['pica_pesoPostProcesamiento'],
            pica_merma=request.POST['pica_merma'],
            pica_check=request.POST['pica_check']
        )
        picado.save()
        
         # Guardar los pesos de materias primas
        for materia_prima in materias_primas:
            peso = request.POST.get(f'peso_{materia_prima.id}')
            if peso:
                peso = int(peso)  # Convertir el peso a entero
                picado_materia_prima = PicadoMateriaPrima(
                    picado=picado,
                    materia_prima=materia_prima,
                    cantidad=peso
                )
                picado_materia_prima.save()

                # Deducir la cantidad del inventario
                materia_prima.cantidad_total -= peso
                materia_prima.save()

        return redirect(reverse_lazy('procesamientos_app:caracteristicas_organolepticas', kwargs={'lote': lote}))

    return render(request, 'procesamientos/picado/ingreso_peso_mp.html', {'producto': producto, 'materias_primas': materias_primas})

#Autor: Vivian carolina Hincapie Escobar
@login_required
def caracteristicas_organolepticas_pt(request, lote):
    '''Vista para ingresar las características organolépticas de un producto terminado'''
    # Obtener el objeto ProductoTerminado asociado al número de lote
    producto = get_object_or_404(ProductoTerminado, pt_lote=lote)

    if request.method == 'POST':
        # Procesar el envío del formulario
        caracteristicas_form = CaracteristicasOrganolepticasPTForm(request.POST)
        if caracteristicas_form.is_valid():
            # Crear y guardar una instancia de CaracteristicasOrganolepticasPT
            caracteristicas = caracteristicas_form.save(commit=False)
            caracteristicas.producto = producto
            # Verificar si se han ingresado todas las características
            if (caracteristicas.olor and caracteristicas.sabor and
                    caracteristicas.color and caracteristicas.textura):
                caracteristicas.estado = '0'  # Estado exitoso
            else:
                caracteristicas.estado = '1'  # Estado incompleto
                caracteristicas.save()
                return redirect(reverse_lazy('produ_app:list_produ'))  # Redirigir a la lista de productos si falta alguna característica
            
            caracteristicas.save()
            return redirect(reverse_lazy('procesamientos_app:empaques', kwargs={'lote': lote}))  # Redirigir a la vista de empaques
    else:
        # Renderizar un formulario vacío para las solicitudes GET
        caracteristicas_form = CaracteristicasOrganolepticasPTForm()

    return render(request, 'procesamientos/caracteristicasorganolepticasPt.html', {'producto': producto, 'form': caracteristicas_form})

#Autor: Vivian carolina Hincapie Escobar
@login_required
def empaque_vacio(request, lote):
    '''Vista para ingresar información sobre el empaque y el vacío de un producto terminado'''
    # Obtener el objeto ProductoTerminado asociado al número de lote
    producto = get_object_or_404(ProductoTerminado, pt_lote=lote)

    if request.method == 'POST':
        # Procesar los datos del formulario
        # Crear una instancia de EmpaqueProductoTerminado
        empaque = EmpaqueProductoTerminado(
            pt_lote=producto,
            emp_pesoKg = request.POST['peso_empaque'],
            emp_cantidadBolsas = request.POST['cantidad_empaque']
        )
        empaque.save()

        # Crear una instancia de Vacio
        vacio= Vacio(
           pt_lote=producto,
           cantidad_bolsas_rechazadas= request.POST['bolsas_rechazadas'],
           cantidad_bolsas_liberadas= request.POST['bolsas_liberadas'],
        )
        vacio.save()
        
        return redirect(reverse_lazy('produ_app:list_produ'))  # Redirigir a la lista de productos
    

sistema/templates/procesamientos/equipos/add_equipo.html
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content bg-dark text-white">
      <div class="modal-header">
        <h5 class="modal-title">Agregar Equipo</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="proAddForm" action="{% url 'procesamientos_app:add_equipos' %}" method="POST" class="form-control bg-dark text-white" style="--bs-bg-opacity: .5;">
            {% csrf_token %}
            {% if form.errors  %}
                <div class="alert alert-info"> 
                    {{form.errors.id_equipo.0}}
                    {{form.errors.equi_encargadoCocina.0}}
                    {{form.errors.equi_encargadoEntrega.0}}
                    {{form.errors.equi_nombre.0}}
                    
                </div>
            {% endif %}

            <div class="mx-4 my-2 row">
                
                <div class="mb-3 col-12">
                    <label for="id_equi_encargadoCocina" class="form-label">Nombre Encargado en Cocina: </label>
                    {{form.equi_encargadoCocina}}   
                </div>
        
        
                <div class="mb-3 col-12">
                    <label for="id_equi_encargadoEntrega" class="form-label">Quien lo Entrego:</label>
                    {{form.equi_encargadoEntrega}}   
                </div>

                <div class="mb-3 col-12">
                    <label for="id_equi_nombre" class="form-label">Nombre del Equipo:</label>
                    {{form.equi_nombre}}  
                </div>

                <div class="mb-3 col-12">
                    <label for="id_equi_calidad" class="form-label">Estado:</label>
                    {{form.equi_check}}  
                </div>

                <div class="d-flex justify-content-center">
                    <div class="row">
                        <div class="col">
                            <button class="btn btn-success" type="submit">Guardar</button>
                            &nbsp;
                            <a href="{% url 'procesamientos_app:equipos' %}" type="button" class="btn btn-secondary">Cancelar</a>
                        </div>
                    </div>
                </div>
            </div>
          </form>
        </div>    
    </div>
</div>

<script>
    $(document).ready(function () {
            $('#proAddForm').submit(function (event) {
                event.preventDefault(); // Evita la redirección predeterminada

                $.ajax({
                    type: 'POST',
                    url: $(this).attr('action'),
                    data: $(this).serialize(),
                    success: function (data) {
                        // Verifica la respuesta y actualiza el contenido del modal
                        $('#add_equipos').html(data);
                        $('#add_equipos').modal('hide');
                    },
                    error: function (xhr, status, error) {
                        // Maneja errores de Ajax, si es necesario
                    }
                });
            });
        });
</script>

sistema/templates/procesamientos/equipos/delete_equipo.html
<div class="modal-dialog modal-md" role="document">
    <div class="modal-content bg-dark text-white">
      <div class="modal-header">
        <h5 class="modal-title">Borrar Equipo</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <form action="{% url 'procesamientos_app:delete_equipo' object.id_equipo %}" method="POST" class="form-control bg-dark text-white" style="--bs-bg-opacity: .5;">
              {%csrf_token%}
          
                <div class="row">
                    <div class="col">
                        <h4 style="color: red; font-weight: bolder;">¿Desea borrar equipo: {{object.equi_nombre}} entregado a: {{object.equi_encargadoCocina}}?</h4>
                        <p class="text-center"><i class="fa-solid fa-circle-info"></i> Esta acción será permanente</p>

                    </div>
                </div>

                <div class="row">
                    <div class="col text-center d-flex justify-content-center">
                        <button class="m-2 btn btn-danger" type="submit">Eliminar</button>
                        <button type="button" class="m-2 btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </form>
        </div>
    
    </div>
</div>
    
    </div>
</div>

sistema/templates/procesamientos/equipos/edit_equipo.html
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content bg-dark text-white">
      <div class="modal-header">
        <h5 class="modal-title">Editar Equipo</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="equiEditForm" action="{% url 'procesamientos_app:edit_equipo' object.id_equipo %}" method="POST" class="form-control bg-dark text-white" style="--bs-bg-opacity: .5;">
            {% csrf_token %}
            {% if form.errors  %}
                <div class="alert alert-info">    
                    {{fom.errors}}
                    {{form.errors.id_equipo.0}}
                    {{form.errors.equi_encargadoCocina.0}}
                    {{form.errors.equi_encargadoEntrega.0}}
                    {{form.errors.equi_nombre.0}}
                </div>
            {% endif %}

            <div class="mx-4 my-2 row">
                
                <div class="mb-3 col-12">
                    <label for="id_equi_encargadoCocina" class="form-label">Nombre Encargado en Cocina: </label>
                    {{form.equi_encargadoCocina}}   
                </div>
        
        
                <div class="mb-3 col-12">
                    <label for="id_equi_encargadoEntrega" class="form-label">Quien lo Entrego:</label>
                    {{form.equi_encargadoEntrega}}   
                </div>

                <div class="mb-3 col-12">
                    <label for="id_equi_nombre" class="form-label">Nombre del Equipo:</label>
                    <br>
                    {{form.equi_nombre}}  
                </div>

                <div class="mb-3 col-12">
                    <label for="id_equi_calidad" class="form-label">Check:</label>
                    <br>
                    {{form.equi_check}}  
                </div>

                <div class="d-flex justify-content-center">
                    <div class="row">
                        <div class="col">
                            <button class="btn btn-success" type="submit">Guardar</button>
                            &nbsp;
                            <a href="{% url 'procesamientos_app:equipos' %}" type="button" class="btn btn-secondary">Cancelar</a>
                        </div>
                    </div>
                </div>
            </div>
          </form>
        </div>    
    </div>
</div>

<script>
    $(document).ready(function () {
            $('#equiEditForm').submit(function (event) {
                event.preventDefault(); // Evita la redirección predeterminada

                $.ajax({
                    type: 'POST',
                    url: $(this).attr('action'),
                    data: $(this).serialize(),
                    success: function (data) {
                        // Verifica la respuesta y actualiza el contenido del modal
                        $('#edit_equipo').html(data);
                    },
                    error: function (xhr, status, error) {
                        // Maneja errores de Ajax, si es necesario
                    }
                });
            });
        });
</script>

sistema/templates/procesamientos/equipos/equipos.html
{% extends 'base.html' %}

{% block title %}
    Equipos
{% endblock title %}


{% block content %}
<div class="mt-3 container">
    <div class="card text-bg-dark mb-3">
        <div class="card-header">
            <div class="row">
                <div class="col-6">
                    <a name="" id="" class="btn btn-success" onclick="add_equipos('{% url 'procesamientos_app:add_equipos' %}')" role="button">Agregar Equipos</a>
                </div>
            </div>
            
        </div>
        <div class="card-body">
            <h4 class="card-title">Equipos</h4>
            
            <div class="table-responsive text-center">
                <table class="table table-secondary">
                    <thead>
                        <tr>
                            <th scope="col">Encargado Cocina</th>
                            <th scope="col">Encargado Entrega</th>
                            <th scope="col" class="text-center">Nombre de Equipo Utilizado</th>
                            <th scope="col">Estado</th>
                            <th scope="col" class="text-center">Eliminar</th>

                        </tr>
                    </thead>
                    <tbody>
                        <a onclick="add_equipos('{% url 'procesamientos_app:add_equipos'%}')" type="button" style="color: blue; text-decoration-line: underline;" data-bs-toggle="tooltip" data-bs-placement="right" ></a>
                        {%for p in procesamientos%}
                        <tr>
                            <td>{{p.equi_encargadoCocina}}</td>
                            <td>{{p.equi_encargadoEntrega}}</td>
                            <td><a onclick="edit_equipo('{% url 'procesamientos_app:edit_equipo' p.id_equipo %}')" type="button" style="color: blue; text-decoration-line: underline;" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-title="Editar">{{p.equi_nombre}}</a></td>
                            <td>
                                {% if p.equi_check == '0' %}
                                <p class="text-success">{{p.get_equi_check_display}}</p>
                                {% elif p.equi_check == '1' %}
                                    <p class="text-danger">{{p.get_equi_check_display}}</p> 
                                {% endif %}
                            </td>
                            
                        </td>
                        <td>

                            <a class="btn btn-danger" onclick="delete_equipo('{% url 'procesamientos_app:delete_equipo' p.id_equipo %}')" type="button"><i class="fa-solid fa-trash-can"></i></a>

                        </td>
                        </tr>
                        {%endfor%}

                    </tbody>
                </table>
            </div>
            
        </div>
    </div>

    <div class="row">
        <div class="col">
            <!--Si existe paginacion entonces mostrará el menu-->
            {% if is_paginated %}  
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                    <!--Si existe una pagina anterior mostrará la opcion de atras-->
                    {% if page_obj.has_previous %}   
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}

                    <!--Itera dentro del objeto paginator para mostrar cuantas paginas existen-->
                    {% for pagina in paginator.page_range %}
                        <!--Si la pagina es el mismo numero del objeto, entonces pinte la casilla en azul-->
                        {% if pagina == page_obj.number %} 
                            <li class="page-item active" aria-current="page"><a class="page-link" href="?page={{pagina}}">{{pagina}}</a></li> 
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{pagina}}">{{pagina}}</a></li>
                        {% endif %}    
                    {% endfor %}
                     
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                    </ul>
                </nav>
            {% endif %}
        </div>
    </div>
</div> 
<div class="modal fade" id="add_equipos" role="dialog"></div>
<div class="modal fade" id="delete_equipo" role="dialog"></div>
<div class="modal fade" id="edit_equipo" role="dialog"></div>

{% endblock content %}

{% block extrajs %}
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>

    <script>
        function add_equipos(url){
            var $ = jQuery.noConflict();
            $('#add_equipos').load(url,function(){
                $(this).modal('show');
            }); 
        }

        function delete_equipo(url){
            var $ = jQuery.noConflict();
            $('#delete_equipo').load(url,function(){
                $(this).modal('show');
            }); 
        }

        function edit_equipo(url){
            var $ = jQuery.noConflict();
            $('#edit_equipo').load(url,function(){
                $(this).modal('show');
            }); 
        }

        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
    </script>
{% endblock  %}