sistema/applications/materiaprima/urls.py
from django.urls import path
from applications.users.decorators import admin_required
from . import views

app_name='mp_app'

urlpatterns = [
    path('mpgeneric_list/',admin_required(views.MateriaPrimaGenericaListView.as_view()),name='listaGenerica_mp'),
    path('add_mp_generica/',admin_required(views.MateriaPrimaGenericaCreateView.as_view()),name='add_mp_generica'),
    path('update_mp_generica/<pk>',admin_required(views.MateriaPrimaGenericaUpdateView.as_view()),name='update_mp_generica'),
    path('delete_mp_generica/<pk>',admin_required(views.MateriaPrimaGenericaDeleteView.as_view()),name='delete_mp_generica'),
    path('mp_list/',views.MateriaPrimaListView.as_view(),name='lista_mp'),
    path('mp_caracteristicas/',views.CaracteristicasMateriaPrimaCreateView.as_view(),name='caracteristicas_mp'),
    path('mp_update_caracteristicas/<pk>',views.CaracteristicasMateriaPrimaUpdateView.as_view(),name='updateCaracteristicas_mp'),
    path('desinfeccion_generico/',admin_required(views.DesinfectanteGenericoListView.as_view()),name='desinfeccion_generico'),
    path('add_desinfeccion_generico/',admin_required(views.DesinfectanteGenericoCreateView.as_view()),name='add_desinfeccion_generico'),
    path('update_desinfeccion_generico/<pk>',admin_required(views.DesinfectanteGenericoUpdateView.as_view()),name='update_desinfeccion_generico'),
    path('delete_desinfeccion_generico/<pk>',admin_required(views.DesinfectanteGenericoDeleteView.as_view()),name='delete_desinfeccion_generico'),
    path('mp_desinfeccion/',views.DesinfeccionMateriaPrimaCreateView.as_view(),name='desinfeccion_mp'),
    path('mp_update_desinfeccion/<pk>',views.DesinfeccionMateriaPrimaUpdateView.as_view(),name='updateDesinfeccion_mp'),
    path('mp_detail/<pk>',views.MateriaPrimaDetailView.as_view(),name='detail_mp'),
    path('mp_update/<pk>',views.MateriaPrimaUpdateView.as_view(),name='mp_update'),
    path('mp_audit/',admin_required(views.MateriaAuditListView.as_view()),name='mp_audit'),
    path('materiaprima/export/xls',admin_required(views.export_materiaprima_to_excel), name='export_materiaprima_excel'),
    path('materiaprima/export/cvs',admin_required(views.export_materiaprima_to_csv), name='export_materiaprima_cvs'),

]

sistema/applications/pedidos/urls.py
from django.urls import path
from . import views

app_name='pedidos_app'

urlpatterns = [
    path('list_pedidos/',views.PedidosListView.as_view(),name='list_pedidos'),
    path('pedidos/export/xls', views.export_pedidos_to_excel, name='export_pedidos_excel'),
    path('pedidos/export/csv', views.export_pedidos_to_csv, name='export_pedidos_csv'),
    path('add_pedidos/',views.PedidosCreateView.as_view(),name='add_pedidos'),
    path('add_mp_pedidos/',views.PedidosAddMpCreateView.as_view(),name='add__mp_pedidos'),
    path('add_it_pedidos/',views.PedidosAddInsumosCreateView.as_view(),name='add__it_pedidos'),
    path('add_prov_pedidos/',views.PedidosAddProveedoresCreateView.as_view(),name='add__prov_pedidos'),
    path('update_pedidos/<pk>',views.PedidosUpdateView.as_view(),name='update_pedidos'),
    path('delete_pedidos/<pk>',views.PedidosDeleteView.as_view(),name='delete_pedidos'),
    path('pedidos_audit/',views.PedidosAuditListView.as_view(),name='pedidos_audit'),


    
    





]

sistema/sistema/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.materiaprima.urls')),
    path('', include('applications.users.urls')),
    path('', include('applications.home.urls')),
    path('', include('applications.insumos.urls')),
    path('', include('applications.proveedores.urls')),
    path('', include('applications.pedidos.urls')),
    path('', include('applications.facturas.urls')),
    path('', include('applications.procesamiento.urls')),
    path('', include('applications.productoterminado.urls')),
    path('', include('applications.existencias.urls')),


] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

sistema/applications/insumos/models.py
from django.db import models
from applications.users.models import User

# Create your models here.

class InsumosGenerico(models.Model):
    '''Tabla generica para insumos'''
    it_nombre=models.CharField('Nombre',max_length=50)
    cantidad_total = models.IntegerField('Cantidad Total', default=0)  # Nuevo campo para almacenar la cantidad total
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.it_nombre}"
    
    def actualizar_cantidad_total(self):
        total = sum([insumo.it_cantidad for insumo in self.insumos_set.all()])
        self.cantidad_total = total
        self.save()
    
class Insumos(models.Model):
    
    class Estado(models.TextChoices):
        DISPONIBLE = '0', 'Disponible'
        NO_DISPONIBLE = '1', 'No Disponible'

    it_codigo = models.AutoField(primary_key=True)
    it_nombre = models.ForeignKey(InsumosGenerico, on_delete=models.CASCADE)
    it_cantidad = models.IntegerField('Cantidad')
    it_fechaEntrega = models.DateField('Fecha Entrega')
    it_estado = models.CharField('Estado', max_length=1, choices=Estado.choices)
    deleted = models.BooleanField(default=False)  

    def __str__(self):
        return f"{self.it_codigo}-{self.it_nombre}-{self.it_fechaEntrega}"

    def save(self, *args, **kwargs):
        # Condiciona el estado basándote en el campo it_cantidad
        if self.it_cantidad == 0:
            self.it_estado = self.Estado.NO_DISPONIBLE
        else:
            self.it_estado = self.Estado.DISPONIBLE

        super().save(*args, **kwargs)

class InsumosAudit(models.Model):
    ACTION_CHOICES = [
        ('C', 'Creado'),
        ('U', 'Actualizado'),
        ('D', 'Borrado')
    ]

    insumos = models.ForeignKey(Insumos, on_delete=models.CASCADE, related_name='audit_logs')
    action = models.CharField(max_length=1, choices=ACTION_CHOICES)
    details = models.TextField(blank=True, null=True)
    changed_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    changed_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.get_action_display()} - {self.insumos.it_nombre} ({self.changed_at})'

sistema/applications/pedidos/models.py
# Fecha de Creación: 20/02/2024
# Autor: Vivian Carolina Hincapie Escobar
# Última modificación: 29/04/2024

from django.db import models
from applications.users.models import User
from applications.materiaprima.models import MateriaPrima
from applications.insumos.models import Insumos
from applications.proveedores.models import Proveedores
from django.utils import timezone

class Pedidos(models.Model):
    '''Definición del modelo para los pedidos'''

    # Opciones para el estado del pedido
    ESTADO_CHOICES=(
        ('0','Completo'),
        ('1','Incompleto'),
        ('2','Rechazado'),
    )

    id=models.AutoField('id',primary_key=True)
    ref_pedido=models.IntegerField('Referencia',unique=True)
    pedi_user=models.ForeignKey(User,on_delete=models.CASCADE, null=True, blank= True)
    pedi_fecha=models.DateField('fecha',default=timezone.now)
    pedi_estado=models.CharField('estado',max_length=1, choices=ESTADO_CHOICES)
    pedi_comprobatePago=models.CharField('Comprobante Pago',max_length=45)
    pedi_proveedor=models.ForeignKey(Proveedores, on_delete=models.CASCADE)
    pedi_materiaprima=models.ManyToManyField(MateriaPrima, blank=True)
    pedi_insumos=models.ManyToManyField(Insumos, blank=True)
    deleted = models.BooleanField(default=False)  # Campo para el borrado lógico

    def __str__(self):
        estado = dict(self.ESTADO_CHOICES)[self.pedi_estado] if self.pedi_estado else 'Estado Desconocido'
        return f"N° Pedido: {self.ref_pedido} - Estado: {estado}"

    def delete(self, using=None, keep_parents=False):
        '''Función para borrado lógico'''
        self.deleted = True # Marcar como inactivo en lugar de eliminar
        self.save(using=using)

class PedidosAudit(models.Model):
    '''Definición del modelo para el registro de auditoría de pedidos'''

    ACTION_CHOICES = [
        ('C', 'Creado'),
        ('U', 'Actualizado'),
        ('D', 'Borrado')
    ]

    changed_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    pedido = models.ForeignKey(Pedidos,on_delete=models.CASCADE, related_name='pedidos_logs')
    action = models.CharField(max_length=1, choices=ACTION_CHOICES)
    details = models.TextField(blank=True, null=True)
    changed_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.get_action_display()} - {self.changed_by} ({self.changed_at})'

sistema/templates/pedidos/add_it_pedidos.html
<!-- 
Titulo: Modal para registrar insumos en pedidos dentro del sistema
Fecha Elaboracion: 23/02/2024 
Elaborado por: Vivian Carolina Hincapie Escobar 
Última actualización: 15/05/2024
 -->

<div class="modal-dialog modal-md" role="document">
    <div class="modal-content bg-dark text-white">
      <div class="modal-header">
        <h5 class="modal-title">Agregar Insumos</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <form id="pedidoAddInsumosForm" action="{% url 'pedidos_app:add__it_pedidos' %}" method="POST" class="form-control bg-dark text-white" style="--bs-bg-opacity: .5;">
              {%csrf_token%}
          
              {% if form.errors %}
                    <div class="alert alert-info">
                        {{form.errors.it_nombre.0}}
                        {{form.errors.it_cantidad.0}}
                    </div>
                {% endif %}

                <div class="mx-4 my-2 row">
                    
                    <div class="mb-3 col-12">
                        <label for="id_mp_nombre" class="form-label">Implemento: </label>
                        {{form.it_nombre}}   
                    </div>
              
               
                    <div class="row">
                        <div class="col-12">
                            <label for="id_mp_cantidad" class="form-label">Cantidad: </label>
                        </div>
                        <div class="input-group mb-3 col-12">
                            {{form.it_cantidad}}
                            <span class="input-group-text">Uds</span>
                        </div>
                    </div>

                    <div class="mb-3 col-12">
                        <label for="id_it_fechaEntrega" class="form-label">Fecha de Entrega:</label>
                        <div class="cont-fecha"> {{form.it_fechaEntrega}}</div>
                         
                    </div>

                    <div class="mb-3 col-12">
                        <label for="id_imp_lote" class="form-label">Estado: </label>
                        {{form.it_estado}}
                    </div>

      
                <div class="row">
                    <div class="col text-center d-flex justify-content-center">                        
                        <button class="m-2 btn btn-success" type="submit">Guardar</button>
                        &nbsp;
                        <button type="button" class="m-2 btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </form>
        </div>
    
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#pedidoAddInsumosForm').submit(function (event) {
            event.preventDefault(); // Evita la redirección predeterminada

            $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                data: $(this).serialize(),
                success: function (data) {
                // Verifica la respuesta y actualiza el contenido del modal
                $('#add_it_pedidos').html(data);
                },
                error: function (xhr, status, error) {
                // Maneja errores de Ajax, si es necesario
                }
            });
        });
    });
</script>    

sistema/templates/pedidos/add_pedidos.html
<!-- 
Titulo: Modal para registrar un  pedidos dentro del sistema
Fecha Elaboracion: 22/02/2024 
Elaborado por: Vivian Carolina Hincapie Escobar 
Última actualización: 06/05/2024
 -->

{% extends "base.html" %}

{% block title %} 
Añadir Pedidos Recibidos 
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            <h1 style="color: #fff;">Agregar Pedidos</h1>
        </div>
    </div>

    <div class="mt-4 row justify-content-center">
        <div class="col-md-7">
            <form action="" method="POST" class="form-control bg-dark text-white" style="--bs-bg-opacity: .5;">
                {% csrf_token %}

                {% if form.errors %}
                    <div class="alert alert-info">
                        {{ form.errors.pedi_fecha.0 }}
                    </div>
                {% endif %}

                <div class="mx-6 my-2 row">

                    <div class="mb-3 col-md-6 col-12">
                        <label for="id_mp_nombre" class="form-label">Tipo de pedido: </label>
                        {{ form.tipo_pedido }}
                    </div>

                    <div class="mb-3 col-md-6 col-12">
                        <label for="id_mp_nombre" class="form-label">Referencia del pedido: </label>
                        {{ form.ref_pedido }}
                    </div>

                    <div class="mb-3 col-md-6 col-12">
                        <label for="id_imp_lote" class="form-label">Estado: </label>
                        {{ form.pedi_estado }}
                    </div>

                    <div class="mb-3 col-md-6 col-12">
                        <label for="id_imp_lote" class="form-label">Proveedor: </label>
                        <div class="row">
                            <div class="col-10">
                                {{ form.pedi_proveedor }}
                            </div>
                            <div class="col">
                                <a onclick="abrir_modal_add_prov('{% url 'pedidos_app:add__prov_pedidos' %}')" type="button" style="color: greenyellow;" class=""><i class="fa-solid fa-plus fa-xl"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="mb-3 col-md-6 col-12">
                        <label for="id_imp_lote" class="form-label">N° Comprobante: </label>
                        {{ form.pedi_comprobatePago }}
                    </div>

                    <div class="mb-3 col-12">
                        <label for="id_mp_fechavencimiento" class="form-label">Fecha de Recibido:</label>
                        <div class="cont-fecha">{{ form.pedi_fecha }}</div>
                    </div>

                    <div class="mb-3 col-12">
                        <label for="id_imp_lote" class="form-label">Materia Prima: </label>
                        <div class="row">
                            <div class="col-9">
                                {{ form.pedi_materiaprima }}
                            </div>
                            <div class="col">
                                <a onclick="abrir_modal_add_mp('{% url 'pedidos_app:add__mp_pedidos' %}')" type="button" style="color: greenyellow;" class="m-3"><i class="fa-solid fa-plus fa-xl"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="mb-3 col-12">
                        <label for="id_imp_lote" class="form-label">Insumos: </label>
                        <div class="row">
                            <div class="col-9">
                                {{ form.pedi_insumos }}
                            </div>
                            <div class="col">
                                <a onclick="abrir_modal_add_it('{% url 'pedidos_app:add__it_pedidos' %}')" type="button" style="color: greenyellow;" class="m-3"><i class="fa-solid fa-plus fa-xl"></i></a>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col d-flex justify-content-center">
                            <button class="btn btn-success" type="submit">Guardar</button>
                            &nbsp;
                            &nbsp;
                            <a href="{% url 'pedidos_app:list_pedidos' %}" type="button" class="btn btn-secondary">Cancelar</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="add_mp_pedidos" role="dialog"></div>
<div class="modal fade" id="add_it_pedidos" role="dialog"></div>
<div class="modal fade" id="add_prov_pedidos" role="dialog"></div>

{% endblock %}

{% block extrajs %}
<script type="text/javascript">
    function toggleInsumosField(value) {
        const insumosField = document.getElementById('id_pedi_insumos');
        insumosField.disabled = value === '0';

        const materiapField = document.getElementById('id_pedi_materiaprima');
        materiapField.disabled = value === '1';
    }

    // Trigger the initial state when the page loads
    toggleInsumosField(document.getElementById('id_tipo_pedido').value);

    async function abrir_modal_add_mp(url) {
        const response = await fetch(url);
        const html = await response.text();
        document.getElementById('add_mp_pedidos').innerHTML = html;
        $('#add_mp_pedidos').modal('show');
    }

    async function abrir_modal_add_it(url) {
        const response = await fetch(url);
        const html = await response.text();
        document.getElementById('add_it_pedidos').innerHTML = html;
        $('#add_it_pedidos').modal('show');
    }

    async function abrir_modal_add_prov(url) {
        const response = await fetch(url);
        const html = await response.text();
        document.getElementById('add_prov_pedidos').innerHTML = html;
        $('#add_prov_pedidos').modal('show');
    }
</script>
{% endblock %}

sistema/templates/pedidos/add_prov_pedidos.html
<!-- 
Titulo: Modal para registrar un proveedor en pedidos dentro del sistema
Fecha Elaboracion: 23/02/2024 
Elaborado por: Vivian Carolina Hincapie Escobar 
Última actualización: 26/04/2024
 -->

 <div class="modal-dialog modal-md" role="document">
    <div class="modal-content bg-dark text-white">
        <div class="modal-header">
            <h5 class="modal-title">Agregar Proveedor</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <!-- Formulario para agregar un proveedor -->
            <form id="pedidoAddProvForm" action="{% url 'pedidos_app:add__prov_pedidos' %}" method="POST" class="form-control bg-dark text-white" style="--bs-bg-opacity: .5;">
                {% csrf_token %}
                
                {% if form.errors %}
                    <div class="alert alert-info">
                        {{ form.errors.prov_nombre.0 }}
                        {{ form.errors.prov_telefono.0 }}
                    </div>
                {% endif %}

                <div class="mx-4 my-2 row">
                    <div class="mb-3 col-12">
                        <label for="id_mp_nombre" class="form-label">NIT: </label>
                        {{ form.nit }}   
                    </div>
              
                    <div class="mb-3 col-12">
                        <label for="id_mp_fechallegada" class="form-label">Razón Social:</label>
                        {{ form.prov_nombre }}   
                    </div>

                    <div class="mb-3 col-12">
                        <label for="id_mp_fechavencimiento" class="form-label">Teléfono</label>
                        <br>
                        {{ form.prov_telefono }}  
                    </div>
                </div>

                <div class="row">
                    <div class="col text-center d-flex justify-content-center">                        
                        <!-- Botón para guardar el proveedor -->
                        <button class="m-2 btn btn-success" type="submit">Guardar</button>
                        &nbsp;
                        <!-- Botón para cerrar el modal -->
                        <button type="button" class="m-2 btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    // Script jQuery para enviar el formulario a través de AJAX
    $(document).ready(function () {
        $('#pedidoAddProvForm').submit(function (event) {
            event.preventDefault(); // Evita la redirección predeterminada del formulario

            $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                data: $(this).serialize(),
                success: function (data) {
                    // Verifica la respuesta y actualiza el contenido del modal
                    $('#add_prov_pedidos').html(data);
                },
                error: function (xhr, status, error) {
                    // Maneja errores de Ajax, si es necesario
                }
            });
        });
    });
</script>

sistema/templates/pedidos/list_pedidos.html
<!-- 
Titulo: Template para mostrar la lista de pedidos registrados en el sistema
Fecha Elaboracion: 22/02/2024 
Elaborado por: Vivian Carolina Hincapie Escobar 
Última actualización: 17/05/2024
 -->

 {% extends 'base.html' %} <!-- Extiende la plantilla base.html -->

 {% block title %}
     Recepción de Pedidos <!-- Título de la página -->
 {% endblock title %}
 
 {% block content %}
 <div class="mt-3">
     <!-- Muestra mensajes de éxito si existen -->
     {% if messages %}
         {% for message in messages %}
             <div class="alert alert-success alert-dismissible fade show" role="alert">
                 {{ message|safe }}
                 <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
             </div>                      
         {% endfor %}
     {% endif %}
     <div class="card text-bg-dark mb-3">
         <div class="card-header">
             <div class="row">
                 <!-- Botón para agregar un nuevo pedido -->
                 <div class="col-6">
                     <a class="btn btn-success" href="{% url 'pedidos_app:add_pedidos' %}" role="button">Agregar Pedido Recibido</a>
                 </div>
                 
                 <!-- Formulario de búsqueda -->
                 <div class="col-6">
                     <form class="d-flex" role="search">
                         {% csrf_token %}
                         <input class="form-control me-2" type="search" placeholder="Buscar Pedido" aria-label="Search" name="kword" id="kword">
                         <button class="btn btn-outline-success" type="submit">Buscar</button>
                     </form>
                 </div>
             </div>
         </div>
         <div class="card-body">
             <div class="cart-title">
                 <div class="mb-2 row">
                     <div class="col-4">
                         <h4>Pedidos Registrados</h4>
                     </div>
                     
                     <div class="col-8 d-flex justify-content-end gap-2">
                         <!-- Menú desplegable para descargar los pedidos en diferentes formatos -->
                         <div class="dropdown">
                             <a href="#" class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Descargar</a>
                             <ul class="dropdown-menu">
                                 <li><a class="dropdown-item" href="{% url 'pedidos_app:export_pedidos_excel' %}">Excel</a></li>
                                 <li><a class="dropdown-item" href="{% url 'pedidos_app:export_pedidos_csv' %}">CSV</a></li>
                               </ul>
                         </div>
                     </div>
                 </div>
             </div>
             
             <div class="table-responsive">
                 <table class="table table-secondary text-center">
                     <thead>
                         <tr>
                             <th scope="col">Referencia</th>
                             <th scope="col">Responsable</th>
                             <th scope="col">Fecha de Recibido</th>
                             <th scope="col">Estado</th>
                             <th scope="col">Comprobante de Pago</th>
                             <th scope="col">Proveedor</th>
                             <th scope="col">Materia Prima</th>
                             <th scope="col">Implementos de Trabajo</th>
                             <th scope="col">Detalles</th>               
                         </tr>
                     </thead>
                     <tbody>
                         <!-- Itera sobre los pedidos y muestra cada uno -->
                         {% for p in pedidos %}
                         <tr>
                             <td>
                                 <a href="{% url 'pedidos_app:update_pedidos' p.id %}" type="button" style="color: blue; text-decoration-line: underline;" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-title="Editar">{{ p.ref_pedido }}</a>
                             </td>
                             <td>{{ p.pedi_user.name }} {{ p.pedi_user.last_name }}</td>
                             <td>{{ p.pedi_fecha|date:"d/m/y" }}</td>
                             
                             <!-- Muestra el estado del pedido con un color diferente según su valor -->
                             {% if p.pedi_estado == '0' %}
                                 <td class="table-success">{{ p.get_pedi_estado_display }}</td>
                             {% elif p.pedi_estado == '1' %}
                                 <td class="table-warning">{{ p.get_pedi_estado_display }}</td> 
                             {% else %}
                                 <td class="table-danger">{{ p.get_pedi_estado_display }}</td>
                             {% endif %}
                             
                             <td>{{ p.pedi_comprobatePago }}</td>
                             <td>{{ p.pedi_proveedor.prov_nombre }}</td>
                             <td>
                                 <!-- Muestra la lista de materia prima del pedido -->
                                 {% if p.pedi_materiaprima.all %}
                                     <ul>
                                         {% for materia_prima in p.pedi_materiaprima.all %}
                                             <li>
                                                 <a href="{% url 'mp_app:detail_mp' pk=materia_prima.pk %}" type="button" style="color: blue; text-decoration-line: underline;" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-title="Ver">{{ materia_prima.mp_nombre }}</a>
                                             </li><br>
                                         {% endfor %}   
                                     </ul>
                                 {% else %}
                                     -
                                 {% endif %}
                             </td>
                             <td>
                                 <!-- Muestra la lista de implementos de trabajo del pedido -->
                                 {% if p.pedi_insumos.all %}
                                     <ul>
                                         {% for insumos in p.pedi_insumos.all %}
                                             <li>{{ insumos.it_nombre }}</li><br>
                                         {% endfor %}   
                                     </ul>
                                 {% else %}
                                     -
                                 {% endif %}
                             </td>
                             <td>
                                 <!-- Botón para eliminar el pedido -->
                                 <a class="m-2 btn btn-danger" onclick="delete_pedido('{% url 'pedidos_app:delete_pedidos' p.id %}')" type="button">
                                     <i class="fa-solid fa-trash-can"></i>
                                 </a>
                             </td>                                                        
                         </tr>
                         {% endfor %}
                     </tbody>
                 </table>
             </div>
         </div>
     </div>
 
     <div class="d-flex justify-content-center">
         <div class="row">
             <div class="col">
                 <!-- Muestra la paginación si es necesaria -->
                 {% if is_paginated %}
                     <nav aria-label="Page navigation example">
                         <ul class="pagination">
                             {% if page_obj.has_previous %}
                                 <li class="page-item">
                                     <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                         <span aria-hidden="true">&laquo;</span>
                                     </a>
                                 </li>
                             {% endif %}
                             {% for pagina in paginator.page_range %}
                                 {% if pagina == page_obj.number %}
                                     <li class="page-item active" aria-current="page">
                                         <a class="page-link" href="?page={{ pagina }}">{{ pagina }}</a>
                                     </li>
                                 {% else %}
                                     <li class="page-item">
                                         <a class="page-link" href="?page={{ pagina }}">{{ pagina }}</a>
                                     </li>
                                 {% endif %}
                             {% endfor %}
                             {% if page_obj.has_next %}
                                 <li class="page-item">
                                     <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                         <span aria-hidden="true">&raquo;</span>
                                     </a>
                                 </li>
                             {% endif %}
                         </ul>
                     </nav>
                 {% endif %}
             </div>
         </div>
     </div>
 </div>  
 
 <!-- Modal para eliminar pedidos -->
 <div class="modal fade" id="delete_pedidos" role="dialog"></div>
 
 {% endblock content %}
 
 {% block extrajs %}
 <!-- Script para manejar la eliminación de pedidos y los tooltips -->
 <script>
     function delete_pedido(url){
         var $ = jQuery.noConflict();
         $('#delete_pedidos').load(url, function(){
             $(this).modal('show');
         }); 
     }
 
     const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
     const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
 </script>
 {% endblock %}
 