sistema/applications/home/urls.py
from django.urls import path
from . import views

app_name='home_app'

urlpatterns = [
    path('home/',views.Home.as_view(),name='home'),
    path('audit_index/',views.AuditViews.as_view(),name='auditorias_index'),
    path('generic_index/',views.GenericsViews.as_view(),name='genericas_index'),
]

sistema/applications/insumos/urls.py
from django.urls import path
from applications.users.decorators import admin_required
from . import views

app_name='insumos_app'

urlpatterns = [
    path('list_insumos_generico/',admin_required(views.InsumosGenericoListView.as_view()),name='list_insumos_generico'),
    path('add_insumos_generico/',admin_required(views.InsumosGenericoCreateView.as_view()),name='add_insumos_generico'),
    path('update_insumos_generico/<pk>',admin_required(views.InsumosGenericoUpdateView.as_view()),name='update_insumos_generico'),
    path('delete_insumos_generico/<pk>',admin_required(views.InsumosGenericoDeleteView.as_view()),name='delete_insumos_generico'),
    path('list_insumos/',views.InsumosListView.as_view(),name='list_insumos'),
    path('update_insumos/<pk>',views.InsumosUpdateView.as_view(),name='update_insumos'),
    path('insumos_audit/',admin_required(views.InsumosAuditListView.as_view()),name='insumos_audit'),
    path('insumos/export/xls',admin_required(views.export_insumos_to_excel), name='export_insumos_excel'),
    path('insumos/export/cvs',admin_required(views.export_insumos_to_csv), name='export_insumos_cvs'),
]

sistema/applications/pedidos/urls.py
from django.urls import path
from . import views

app_name='pedidos_app'

urlpatterns = [
    path('list_pedidos/',views.PedidosListView.as_view(),name='list_pedidos'),
    path('pedidos/export/xls', views.export_pedidos_to_excel, name='export_pedidos_excel'),
    path('pedidos/export/csv', views.export_pedidos_to_csv, name='export_pedidos_csv'),
    path('add_pedidos/',views.PedidosCreateView.as_view(),name='add_pedidos'),
    path('add_mp_pedidos/',views.PedidosAddMpCreateView.as_view(),name='add__mp_pedidos'),
    path('add_it_pedidos/',views.PedidosAddInsumosCreateView.as_view(),name='add__it_pedidos'),
    path('add_prov_pedidos/',views.PedidosAddProveedoresCreateView.as_view(),name='add__prov_pedidos'),
    path('update_pedidos/<pk>',views.PedidosUpdateView.as_view(),name='update_pedidos'),
    path('delete_pedidos/<pk>',views.PedidosDeleteView.as_view(),name='delete_pedidos'),
    path('pedidos_audit/',views.PedidosAuditListView.as_view(),name='pedidos_audit'),


    
    





]

sistema/applications/users/urls.py
#Fecha de Creación: 02/02/2024
#Autor: Vivian Carolina Hincapie Escobar
#Última modficación: 15/05/2024

from django.urls import path
from . import views
from .decorators import admin_required  # Importa el decorador personalizado

app_name='users_app'

urlpatterns = [
    path('',views.LogIn.as_view(),name='login'),
    path('list_user/',admin_required(views.UsersListView.as_view()),name='list_user'),
    path('user/export/xls',admin_required(views.export_users_to_excel), name='export_users_excel'),
    path('user/export/cvs',admin_required(views.export_users_to_csv), name='export_users_csv'),
    path('add_user/',admin_required(views.UserRegisterView.as_view()),name='add_user'),
    path('edit_user/<pk>',admin_required(views.UserUpdateView.as_view()),name='edit_user'),
    path('delete_user/<pk>',admin_required(views.UserDeleteView.as_view()),name='delete_user'),
    path('logout/',views.LogOut.as_view(),name='logout'),
    path('user_audit/',admin_required(views.UserAuditListView.as_view()),name='user_audit'),
]

sistema/sistema/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.materiaprima.urls')),
    path('', include('applications.users.urls')),
    path('', include('applications.home.urls')),
    path('', include('applications.insumos.urls')),
    path('', include('applications.proveedores.urls')),
    path('', include('applications.pedidos.urls')),
    path('', include('applications.facturas.urls')),
    path('', include('applications.procesamiento.urls')),
    path('', include('applications.productoterminado.urls')),
    path('', include('applications.existencias.urls')),


] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

sistema/templates/base.html
<!-- 
Titulo: Plantilla base para la aplicación
Fecha Elaboracion: 02/02/2024 
Última actualización: 02/06/2024
 -->

{%load static%}
<!doctype html>
<html lang="es">
    <head>
        <title>{%block title%}{%endblock%}</title> <!-- Título de la página -->
        <!-- meta tags requeridos -->
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        <!-- Enlaces a archivos estáticos -->
        <link rel="icon" href="{% static 'img/icon.png' %}" type="image/x-icon">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.11.1/dist/sweetalert2.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css'%}">
        <link rel="stylesheet" href="{% static 'css/estilos.css'%}">
    </head>

    <body>

        <div class="wrapper">
            <!-- Sidebar -->
            <aside id="sidebar">
                <!-- Logo y nombre de la aplicación -->
                <div class="d-flex">
                    <button class="toggle-btn" type="button">
                        <img src="{% static 'img/Logotacomas.png' %}" alt="">
                    </button>
                    <div class="mt-2 sidebar-logo">
                        <a href="{% url 'home_app:home' %}">Taco Mas</a> 
                        <!-- Verifica el tipo de usuario y muestra su rol -->
                        {% if user.is_admin %}
                            <p style="color: #fff;">Administrador</p>
                        {% else %}
                            <p style="color: #fff;">Operario</p>
                        {% endif %}  
                    </div>
                        
                </div>
                <hr>
                    
                <ul class="sidebar-nav">
                    <!-- Elementos de navegación -->
                    {% if user.is_admin %}
                    <!-- Si el usuario es administrador, muestra estas opciones -->
                    <li class="sidebar-item">
                        <a href="{% url 'users_app:list_user' %}" class="sidebar-link">
                            <i class="fa-solid fa-users pe-2"></i>
                                <span>Usuarios</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a href="#" class="sidebar-link collapsed has-dropdown" data-bs-toggle="collapse"
                        data-bs-target="#compras" aria-expanded="false" aria-controls="compras">
                            <i class="fa-solid fa-truck pe-2"></i>
                                <span>Compras</span>
                        </a>
                        <ul id="compras" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                            <li class="sidebar-item">
                                <a href="{% url 'pedidos_app:list_pedidos' %}" class="sidebar-link"><i class="fa-solid fa-clipboard-list"></i> Pedidos</a>
                            </li>
                            <li class="sidebar-item">
                                <a href="{% url 'proveedores_app:list_proveedores' %}" class="sidebar-link"><i class="fa-solid fa-clipboard-user"></i> Proveedores</a>
                            </li>
                            <li class="sidebar-item">
                                <a href="{% url 'facturas_app:list_factura' %}" class="sidebar-link"><i class="fa-solid fa-file-invoice-dollar"></i> Facturas</a>
                            </li>
                        </ul>
                    </li>

                    <li class="sidebar-item">
                        <a href="#" class="sidebar-link collapsed has-dropdown" data-bs-toggle="collapse"
                        data-bs-target="#modulos" aria-expanded="false" aria-controls="modulos">
                        <i class="fa-solid fa-wrench"></i>
                                <span>Herramientas Administrador</span>
                        </a>
                        <ul id="modulos" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                            <li class="sidebar-item">
                                <a href="{% url 'home_app:genericas_index' %}" class="sidebar-link">Tablas Genéricas</a>
                            </li>
                            <li class="sidebar-item">
                                <a href="{% url 'home_app:auditorias_index' %}" class="sidebar-link">Tablas de Auditoria</a>
                            </li>
                        </ul>
                    </li>
                    {% endif %}

                    <!-- Elementos de navegación comunes para todos los usuarios -->
                    <li class="sidebar-item">
                        <a href="#" class="sidebar-link collapsed has-dropdown" data-bs-toggle="collapse"
                            data-bs-target="#existencias" aria-expanded="false" aria-controls="existencias">
                            <i class="fa-regular fa-square-check pe-2"></i>
                              <span>Existencias</span>
                        </a>
                        <ul id="existencias" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                            <li class="sidebar-item">
                                <a href="{% url 'existencias_app:stock_mp' %}" class="sidebar-link">Stock Materia Prima</a>
                            </li>
                            <li class="sidebar-item">
                                <a href="{% url 'existencias_app:stock_pt' %}" class="sidebar-link">Stock Producto Terminado</a>
                            </li>
                            <li class="sidebar-item">
                                <a href="{% url 'existencias_app:stock_it' %}" class="sidebar-link">Stock Insumos</a>
                            </li>
                        </ul>
                    </li>
                    
                    <li class="sidebar-item">
                        <a href="#" class="sidebar-link collapsed has-dropdown" data-bs-toggle="collapse"
                            data-bs-target="#producto" aria-expanded="false" aria-controls="producto">
                            <i class="fa-solid fa-seedling pe-2"></i>
                              <span>Producto</span>
                        </a>
                        <ul id="producto" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                            <li class="sidebar-item">
                                <a href="{% url 'mp_app:lista_mp' %}" class="sidebar-link">Materia Prima</a>
                            </li>
                            <li class="sidebar-item">
                                <a href="{% url 'produ_app:list_produ' %}" class="sidebar-link">Producto Terminado</a>
                            </li>
                            <li class="sidebar-item">
                                <a href="{% url 'insumos_app:list_insumos' %}" class="sidebar-link">Insumos</a>
                            </li>
                        </ul>
                    </li>

                    <li class="sidebar-item">
                        <a href="{% url 'procesamientos_app:procesamientos' %}" class="sidebar-link">
                            <i class="fa-solid fa-arrows-spin pe-2"></i>
                                <span>Procesamiento</span>
                        </a>
                    </li>
                    
                </ul>
                <hr>
                <!-- Pie de página del Sidebar -->
                <div class="sidebar-footer">
                    <a href="{% url 'users_app:logout' %}" class="sidebar-link">
                        <i class="fa-solid fa-right-from-bracket pe-2"></i>
                            <span>Cerrar Sesión</span>
                    </a>
                </div>
            </aside>
            <!-- Contenido principal -->
            <div class="main">
                <main class="content px-3 py-2">
                    <div class="container-fluid">
                        <div class="mb-3">
                            {%block content%}
                                <!-- Aquí se inserta el contenido específico de cada página -->
                            {%endblock%}
                        </div>
                    </div>
                </main>
            </div>
        </div>
        

        <!-- JavaScript scripts --> 
        <script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/909a90592e.js" crossorigin="anonymous"></script>   
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>    
        <script src="{% static 'js/scripts.js' %}"></script>

        <!-- Bloque adicional para scripts personalizados -->
        {% block extrajs %}
            
        {% endblock extrajs %}
      
    </body>
</html>